### ISSUE TITLE
ValueError: invalid literal for float

### ISSUE THREAD

**Issue by PatMyron** [matstc/shell-profiler#1]
`Pats-MacBook-Pro  ~/Documents/GitHub/shell-profiler $ profile test-file.sh`
```
--- END OF PROFILING ---
Traceback (most recent call last):
  File "./profile", line 65, in <module>
    profiling_with_timings = map(collect_timings, tokenized_trace, range(len(tokenized_trace)))
  File "./profile", line 25, in collect_timings
    timing = float(tokenized_trace[index+1][1]) - float(tokens[1]) 
ValueError: invalid literal for float(): 1542746022.N
```
Run on MacOS Mojave 10.14.1 (18B75) terminal
`$ bash --version`
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
Copyright (C) 2007 Free Software Foundation, Inc.
`$ python --version`
Python 2.7.15

**Comment by matstc** [comment]
Thanks @PatMyron. Though I could not reproduce this. Can you try again with the `--debug` flag and share the output?

You'll have to pull the latest to get the flag.

**Comment by PatMyron** [comment]
@matstc 
[stacktrace.txt](https://github.com/matstc/shell-profiler/files/2601728/stacktrace.txt)

**Comment by matstc** [comment]
@PatMyron  I applied a fix on master. Can you pull and try again?

**Comment by PatMyron** [comment]
@matstc worked 🎉 thank you so much!
